### ISSUE TITLE
Does it detect front matter of markdown as YAML?

### ISSUE THREAD

**Issue by Freed-Wu** [Shougo/context_filetype.vim#56]
This is a `test.md`:

```markdown
---
title: "Habits"
author: John Doe
date: March 22, 2005
output:
  pdf_document:
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
      after_body: doc_suffix.tex
---

# H1 Title

## H2 Title
```

I try [caw.vim](https://github.com/tyru/caw.vim) and I expect:

```markdown
---
title: "Habits"
author: John Doe
# date: March 22, 2005
output:
  pdf_document:
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
      after_body: doc_suffix.tex
---

# H1 Title

## H2 Title
```

However:

```markdown
---
title: "Habits"
author: John Doe
<!-- date: March 22, 2005 -->
output:
  pdf_document:
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
      after_body: doc_suffix.tex
---

# H1 Title

## H2 Title
```

I notice [caw.vim](https://github.com/tyru/caw.vim) use [context_filetype.vim](https://github.com/Shougo/context_filetype.vim). So does it detect front matter of markdown as YAML?

**Comment by Shougo** [comment]
I will test it.  But I think the pattern is not supported yet.

**Comment by Freed-Wu** [comment]
> I will test it

Thanks.
If it support, I should file a bug report to [caw.vim](https://github.com/tyru/caw.vim).
If it doesn't support, I should file a feature request to [context_filetype.vim](https://github.com/Shougo/context_filetype.vim).

**Comment by Shougo** [comment]
I have tested it and `context_filetype` works.

**Comment by Shougo** [comment]
I have tested `caw.vim` and it is strange.

```
---
title: "Habits"
author: John Doe
/* date: March 22, 2005 */
output:
  pdf_document:
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
      after_body: doc_suffix.tex
---

# H1 Title

## H2 Title
```
